FROM python:3.8-slim-buster
RUN apt update && apt install libpq-dev gcc -y
RUN python3 -m ensurepip --upgrade
COPY requirements_discord.txt .
RUN pip install -r requirements_discord.txt
COPY . .

CMD ["python3","bot.py"]
