version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_pw
      POSTGRES_DB_FILE: /run/secrets/db
    secrets:
      - user
      - postgres_pw
      - db
    ports:
      - '0.0.0.0:5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      main:
        aliases:
          - db
  discord:
    build:
      context: .
      dockerfile: Dockerfile.discord
    restart: always
    depends_on:
      - db
    networks:
      main:
        aliases:
          - discord
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    depends_on:
      - db
    ports:
      - '0.0.0.0:8080:80'
    networks:
      main:
        aliases:
          - api
  loader:
    build:
      context: .
      dockerfile: Dockerfile.load
    restart: always
    depends_on:
      - db
    networks:
      main:
        aliases:
          - loader
volumes:
  db:
    driver: local
networks:
  main:
secrets:
  postgres_pw:
    file: postgres_pw.txt
  user:
    file: postgres_user.txt
  db:
    file: postgres_db.txt
