FROM python:3.8-slim-buster
RUN apt update && apt install libpq-dev gcc -y
RUN python3 -m ensurepip --upgrade
COPY requirements_api.txt .
RUN pip install -r requirements_api.txt
COPY . .

COPY app.py /home/app.py
ENTRYPOINT FLASK_APP=/home/app.py flask run --host=0.0.0.0
