version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=maindb
    ports:
      - '0.0.0.0:5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      main:
        aliases:
          - db
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    depends_on:
      - db
    ports:
      - '0.0.0.0:8080:80'
    networks:
      main:
        aliases:
          - api    
volumes:
  db:
    driver: local
networks:
  main:
