version: '3.8'
services:
  discord:
    build:
      context: .
      dockerfile: Dockerfile.discord
    image: stakeappgrp.azurecr.io/discord
    restart: always
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 2G
        limits:
          cpus: '1'
          memory: 3G
    networks:
      main:
        aliases:
          - discord
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: stakeappgrp.azurecr.io/api
    restart: always
    ports:
      - '0.0.0.0:80:80'
    networks:
      main:
        aliases:
          - api
  loader:
    build:
      context: .
      dockerfile: Dockerfile.load
    image: stakeappgrp.azurecr.io/loader
    restart: always
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 2G
        limits:
          cpus: '1'
          memory: 3G
    networks:
      main:
        aliases:
          - loader
networks:
  main:
