FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11

RUN apt update && apt install libpq-dev gcc -y
RUN python3 -m ensurepip --upgrade
COPY requirements_api.txt /app/requirements_api.txt
RUN pip install -r /app/requirements_api.txt
COPY .env /app/.env
COPY ./app /app
